### ISSUE TITLE
First stab...

### ISSUE THREAD

**Issue by maranomynet** [maranomynet/DefinitelyTyped#1]
@spacejack FYI, here's where I'm at:

https://github.com/maranomynet/DefinitelyTyped/tree/ospec/types/ospec

The bit I've yet to figure out is what is the most idiomatic way to export the types/interfaces so that they're nice to use/import **and** works with dtslint's `$ExpectType` declarations.

**Comment by spacejack** [comment]
@isiahmeadows Pinging you in case you want to take a look.

@maranomynet Looks good to me! The tests are pretty good as is... I think those can be improved in future if needed.

Since you did the bulk of the work it'd be fair to put yourself as the primary author if you like, followed by @isiahmeadows and myself. Either way it would be good to include him since he's ospec's primary maintainer.

Thank you for taking the initiative on this!

**Comment by maranomynet** [comment]
PR sent: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37645

**Comment by isiahmeadows** [comment]
Left a bunch of comments over there. 🙂
